---
sudo: required
dist: xenial

language: python
python:
  - "2.7"
  - "3.6"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.6.4
  - ANSIBLE_VERSION=2.5.10
  - ANSIBLE_VERSION=2.4.6.0

branches:
  only:
  - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-pip
  - pip install pyOpenSSL

install:
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
