# -*- mode: ruby -*-
# vi: set ft=ruby :
@ansible_home = "/home/vagrant/.ansible"

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider :virtualbox do |v|
    v.name = "vagrant"
    v.memory = 512
    v.cpus = 1
  end

  config.vm.hostname = "vagrant"
  config.vm.network "forwarded_port", guest: 8089, host: 8089
  config.vm.network "forwarded_port", guest: 8443, host: 8443
  config.vm.network "forwarded_port", guest: 9997, host: 9997

  config.vm.synced_folder "../", "#{@ansible_home}/roles/ansible-splunk-common"
  config.vm.provision "shell", inline: "chown vagrant:vagrant #{@ansible_home}"
  config.vm.provision "shell", inline: "apt-get update && apt-get install python-pip -y"
  config.vm.provision "shell", inline: "pip install pyOpenSSL"

  config.vm.define :vagrant do |vagrant|
  end

  config.vm.provision "ansible_local" do |ansible|
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "./test.yml"
    ansible.inventory_path = "./inventory"
    ansible.become = true
  end

end
